### ISSUE TITLE
Single student

### ISSUE THREAD

**Issue by bvandervoorn** [Tools4everBV/HelloID-Conn-Prov-Source-Topicus-ParnasSys#2]
When a Brincode only contains a single student $leerlingen.count will return 22. This because it is a hashtable with 22 variables. 
When you use the action .addRange it results in an error.

To solve this I'd suggest creating an array and adding $leerlingen to the array.

For example:
$leerLingen = ConvertTo-ReturnXmlToLeerlingenlist -ReturnNode $leerLingenReturnNode
$array= @()
$array = $array + $leerlingen
This way .addRange can add $leerlingen without issue.

**Comment by JeroenBL** [comment]
This issue has been open for quite some time without any recent activity. We appreciate all the feedback and contributions.

To keep our issue tracker focused and organized, we are closing this issue. If the problem persists or if there are any new developments, please feel free to reopen the issue or create a new one
